### ISSUE TITLE
"Wasm.instantiateModule() [...] expected version 0b 00 00 00, found 0a 00 00 00 @+4"

### ISSUE THREAD

**Issue by facekapow** [evanw/zeroscript#12]
When running the ThinScript Compiler Demo on Chrome Canary v54, the log just outputs `"Wasm.instantiateModule(): Result = expected version 0b 00 00 00, found 0a 00 00 00 @+4\n"`

I'm guessing this is because the Chrome is following along with the spec and updating the version and ThinScript hasn't caught up yet?

**Comment by binji** [comment]
Yeah, I sent a pull request to update it in https://github.com/evanw/thinscript/pull/8

**Comment by nidin** [comment]
I have forked it and re-created as TurboScript since this project seems dead http://01alchemist.com/projects/turboscript/playground/
