### ISSUE TITLE
Using SquiLu to compile thinscript

### ISSUE THREAD

**Issue by mingodad** [evanw/zeroscript#2]
Hello !
I just saw this project on hacker news and I was looking to do something like this but modifying my fork of squirrel https://github.com/mingodad/squilu and just now I could get it to parse this repository src with few changes.
I saw your other projects and I think that we could join efforts.

Tomorrow I'll see if I get SquiLu to run thinscript, by the way why thinscript if you already has skew ?

Cheers !

**Comment by evanw** [comment]
Thanks for your offer to collaborate. Building a new language and compiler is a large undertaking and it often makes sense to start from an existing project and not from scratch. However, I've got a pretty specific idea of the language I want to create and I want to implement that vision. Starting from somewhere else would ultimately force compromises on the design that would mean steering away from that vision, so I'm not planning on doing that.
